[tool.poetry]
name = "hermes"
version = "0.1.0"
description = "Inference-as-a-Service deployment made simple"
authors = [
    "Alec Gunny <alec.gunny@ligo.org>", "Ethan Marx <emarx@mit.edu>"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
tritonclient = {extras = ["all"], version = "^2.22"}
protobuf = "^3.17"


# client library dependencies
[tool.poetry.group.client]
optional = true

[tool.poetry.group.client.dependencies]
numpy = "^1.22"
requests = "^2.26"


# simple serving wrapper dependencies
[tool.poetry.group.serve]
optional = true

[tool.poetry.group.serve.dependencies]
spython = "^0.2"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.16"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | _build
  | dist
  | docs
)/
'''

[tool.isort]
known_first_party = ["hermes"]
multi_line_output = 3
include_trailing_comma = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
