name: Build and publish Docker image

on:
  push:
    branches:
    - main

env:
  REGISTRY: ghcr.io

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ML4GW'
    strategy:
      fail-fast: false
      matrix:
        trt-version: ["8.2.3", "8.4.1"]
        include:
        - trt-version: 8.2.3
          triton-tag: 22.02
        - trt-version: 8.4.1
          triton-tag: 22.07
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2

    -
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          .github/triton.Dockerfile
          .github/workflows/triton-build.yaml

    -
      name: Log in to container registry
      uses: docker/login-action@master
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -
      name: Triton Server pull-push
      id: gw-iaas-server-container-push
      env:
        TAG: ${{ env.REGISTRY }}/ml4gw/hermes/tritonserver:${{ matrix.triton-tag }}
      run: |
        docker build \
            -f .github/triton.Dockerfile \
            --build-arg TRITON_TAG=${{ matrix.triton_tag }} \
            --build-arg TENSORRT_VERSION=${{ matrix.tensorrt_version }} \
            -t ${{ env.TAG }} \
            .github/
        docker push ${{ env.TAG }}
