name: unit-tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.10]
        poetry-version: [1.2.0a2, 1.2.0b2]
        libs: ["aeriel", "cloudbreak", "quiver", "stillwater"]
    steps:
    - uses: actions/checkout@v2

    # set up a filter so we only test if this lib got touched
    - 
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          lib:
            - 'hermes/hermes.${{ matrix.lib }}/**'

    # set up our environment
    - 
      uses: actions/setup-python@v2
      if: steps.filter.outputs.lib == 'true'
      with:
        python-version: ${{ matrix.python-version }}
    - 
      name: Set up poetry
      if: steps.filter.outputs.lib == 'true'
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    -
      name: Install tox
      if: steps.filter.outputs.lib == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    # run the library's tests
    -
      name: run tests
      if: steps.filter.outputs.lib == 'true'
      run: |
        cd hermes/hermes.${{ matrix.lib }}
        tox
